FROM python:3

USER root

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . .

RUN pip install -r requirements.txt

RUN chmod +x ci_scripts/python-entrypoint.local.sh
CMD ["sh", "ci_scripts/python-entrypoint.local.sh"]
